import React, { createContext, useContext, useEffect, useState } from "react";

// Real i18n for the visible UI chrome (headers, sidebar, key labels).
// Languages: English, Assamese, Bengali, Hindi, Bodo. Selected language is
// persisted in localStorage and applied everywhere via t(key).
export const DICT = {
  en: {
    // Navigation items
    "nav.dashboard": "Dashboard",
    "nav.live-map": "Live Map",
    "nav.ai-predictions": "AI Predictions",
    "nav.route-optimization": "Route Optimization",
    "nav.vehicle-tracking": "Vehicle Tracking",
    "nav.alerts": "Alerts & Notifications",
    "nav.field-reports": "Field Reports",
    "nav.analytics": "Analytics & Reports",
    "nav.users": "Users",
    "nav.emergency": "Emergency Mode",
    "nav.settings": "Settings",
    "nav.consignments": "My Consignments",
    "nav.vehicles": "My Vehicles",
    "nav.tracking": "Live Tracking & GPS",
    "nav.fleet-tracking": "Vehicle Tracking",
    "nav.routes": "Route Planning",
    "nav.history": "Delivery History",
    "nav.reports": "Reports & Analytics",
    "nav.help": "Help & Support",
    "nav.profile": "Profile",
    "nav.adminPortal": "Admin Portal",
    "nav.transporterHub": "Transporter Hub",
    "nav.driverApp": "Driver App",
    "nav.fieldOfficer": "Field Officer",
    "nav.platform": "Platform",
    "nav.howItWorks": "How It Works",
    "nav.intelligence": "Intelligence",
    "nav.solutions": "Solutions",
    "nav.about": "About",
    "nav.login": "Login",
    "nav.getStarted": "Get Started",
    "nav.switch": "Switch",
    "nav.logOut": "Log Out",
    "nav.signOut": "Sign Out",

    // Sidebar Chrome
    "sidebar.brandTagline": "Smart Routes, Safe Deliveries",
    "sidebar.quickActions": "Quick Actions",
    "sidebar.addVehicle": "Add Vehicle",
    "sidebar.createAlert": "Create Alert",
    "sidebar.generateReport": "Generate Report",
    "sidebar.importData": "Import Data",
    "sidebar.systemStatus": "System Status",
    "sidebar.gpsTracking": "GPS Tracking",
    "sidebar.dataSync": "Data Sync",
    "sidebar.aiEngine": "AI Engine",
    "sidebar.serverStatus": "Server Status",
    "sidebar.online": "Online",
    "sidebar.offline": "Offline",
    "sidebar.needHelp": "Need Help?",
    "sidebar.supportDesc": "Our support team is available 24/7 to assist you.",
    "sidebar.contactSupport": "Contact Support",
    "sidebar.liveMode": "Live Mode",
    "sidebar.offlineMode": "Offline Mode",
    "sidebar.liveDesc": "Real-time data active",
    "sidebar.offlineDesc": "Data will sync when online",
    "sidebar.adminUser": "Admin User",
    "sidebar.adminRole": "Government Admin",

    // Top Header Chrome
    "header.searchPlaceholder": "Search vehicles, routes, drivers, alerts, reports...",
    "header.logisticsGrid": "Raahi Logistics Grid",
    "header.vehiclesActive": "Vehicles Active",
    "header.emergencySOS": "Emergency SOS",
    "header.openLiveMap": "Open GIS Live Map Navigator",
    "header.fieldReports": "Field Incident Reports",
    "header.notifications": "Notifications",
    "header.markAllRead": "Mark all read",
    "header.noAlerts": "No active alerts — all clear.",
    "header.settingsProfile": "Settings & Profile",
    "header.supportHelp": "Support & Help",
    "header.signOut": "Sign Out",
    "header.addConsignment": "Add Consignment",
    "header.operator": "Transporter Operator",
    "header.subtitle": "Here's what's happening with your operations today.",
    "header.title": "Let's move every delivery forward.",

    // Dashboard View
    "dashboard.welcome": "Welcome back",
    "dashboard.subtitle": "Here's real-time intelligence across the North Eastern Region today.",
    "dashboard.dataSources": "Data Sources",
    "dashboard.weather": "Weather",
    "dashboard.mlModels": "ML Models",
    "dashboard.vehicles": "Vehicles",
    "dashboard.gps": "GPS",
    "dashboard.live": "LIVE",
    "dashboard.loaded": "loaded",
    "dashboard.inDb": "in DB",
    "dashboard.positionsAvailable": "Positions available",
    "dashboard.awaitingGps": "Awaiting GPS data",
    "dashboard.totalRoutes": "Total Routes Monitored",
    "dashboard.routesAtRisk": "Routes at Risk",
    "dashboard.blockedRoutes": "Blocked Routes",
    "dashboard.activeVehicles": "Active Vehicles",
    "dashboard.deliveriesInTransit": "Deliveries in Transit",
    "dashboard.vsYesterday": "vs yesterday",

    // Common labels & buttons
    "common.goodMorning": "Good Morning",
    "common.goodAfternoon": "Good Afternoon",
    "common.goodEvening": "Good Evening",
    "common.active": "Active",
    "common.resolved": "Resolved",
    "common.critical": "Critical",
    "common.high": "High",
    "common.medium": "Medium",
    "common.low": "Low",
    "common.viewAll": "View All",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",

    // Authentication Form
    "auth.welcomeBack": "Welcome Back!",
    "auth.signInPrompt": "Sign in to continue to",
    "auth.official": "Official",
    "auth.transporter": "Transporter",
    "auth.driver": "Driver",
    "auth.emailOrPhone": "Email or Phone Number",
    "auth.emailPlaceholder": "Enter email or phone number",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot Password?",
    "auth.signIn": "Sign In",
    "auth.signingIn": "Signing In...",
    "auth.securityNotice": "Official DoNER Logistics Portal. 256-bit SSL encrypted.",
    "User Login": "User Login",
    "Official Login": "Official Login",
    "Operator Login": "Operator Login",
  },
  as: {
    // Navigation items (অসমীয়া)
    "nav.dashboard": "ডেছব'ৰ্ড",
    "nav.live-map": "লাইভ মেপ",
    "nav.ai-predictions": "এআই পূৰ্বাভাস",
    "nav.route-optimization": "ৰুট অপ্টিমাইজেচন",
    "nav.vehicle-tracking": "বাহন ট্ৰেকিং",
    "nav.alerts": "সতৰ্কবাণী আৰু জাননী",
    "nav.field-reports": "ফিল্ড প্ৰতিবেদন",
    "nav.analytics": "বিশ্লেষণ আৰু প্ৰতিবেদন",
    "nav.users": "ব্যৱহাৰকাৰীসকল",
    "nav.emergency": "জৰুৰীকালীন অৱস্থা",
    "nav.settings": "ছেটিংছ",
    "nav.consignments": "মোৰ কনছাইনমেন্ট",
    "nav.vehicles": "মোৰ যান-বাহন",
    "nav.tracking": "লাইভ ট্ৰেকিং আৰু জিপিএছ",
    "nav.fleet-tracking": "বাহন ট্ৰেকিং",
    "nav.routes": "ৰুট পৰিকল্পনা",
    "nav.history": "ডেলিভাৰী ইতিহাস",
    "nav.reports": "ৰিপৰ্ট আৰু বিশ্লেষণ",
    "nav.help": "সহায় আৰু সমৰ্থন",
    "nav.profile": "প্ৰফাইল",
    "nav.adminPortal": "এডমিন পৰ্টেল",
    "nav.transporterHub": "পৰিবহণ কেন্দ্ৰ",
    "nav.driverApp": "চালক এপ",
    "nav.fieldOfficer": "ক্ষেত্ৰ বিষয়া",
    "nav.platform": "মঞ্চ",
    "nav.howItWorks": "ই কেনেকৈ কাম কৰে",
    "nav.intelligence": "বুদ্ধিমত্তা",
    "nav.solutions": "সমাধান",
    "nav.about": "বিষয়ে",
    "nav.login": "লগইন",
    "nav.getStarted": "আৰম্ভ কৰক",
    "nav.switch": "সলনি কৰক",
    "nav.logOut": "লগ আউট",
    "nav.signOut": "লগ আউট",

    // Sidebar Chrome
    "sidebar.brandTagline": "বুদ্ধিমান পথ, সুৰক্ষিত বিতৰণ",
    "sidebar.quickActions": "দ্ৰুত কাৰ্যকলাপ",
    "sidebar.addVehicle": "বাহন যোগ কৰক",
    "sidebar.createAlert": "সতৰ্কবাণী সৃষ্টি কৰক",
    "sidebar.generateReport": "প্ৰতিবেদন প্ৰস্তুত কৰক",
    "sidebar.importData": "তথ্য আমদানি কৰক",
    "sidebar.systemStatus": "প্ৰণালীৰ স্থিতি",
    "sidebar.gpsTracking": "জিপিএছ ট্ৰেকিং",
    "sidebar.dataSync": "তথ্য সমলয়",
    "sidebar.aiEngine": "এআই ইঞ্জিন",
    "sidebar.serverStatus": "চাৰ্ভাৰ স্থিতি",
    "sidebar.online": "অনলাইন",
    "sidebar.offline": "অফলাইন",
    "sidebar.needHelp": "সহায় লাগেনে?",
    "sidebar.supportDesc": "আপোনাক সহায় কৰিবলৈ আমাৰ দল ২৪/৭ সাজু।",
    "sidebar.contactSupport": "সহায়তাৰ সৈতে যোগাযোগ",
    "sidebar.liveMode": "লাইভ মোড",
    "sidebar.offlineMode": "অফলাইন মোড",
    "sidebar.liveDesc": "বাস্তৱ-সময় তথ্য সক্ৰিয়",
    "sidebar.offlineDesc": "অনলাইন হ'লে তথ্য সমলয় হ'ব",
    "sidebar.adminUser": "এডমিন ব্যৱহাৰকাৰী",
    "sidebar.adminRole": "চৰকাৰী প্ৰশাসক",

    // Top Header Chrome
    "header.searchPlaceholder": "বাহন, পথ, চালক, সতৰ্কবাণী, প্ৰতিবেদন অনুসন্ধান কৰক...",
    "header.logisticsGrid": "ৰাহী লজিষ্টিকছ গ্ৰীড",
    "header.vehiclesActive": "খন বাহন সক্ৰিয়",
    "header.emergencySOS": "জৰুৰীকালীন এছ.অ’.এছ",
    "header.openLiveMap": "জিআইএছ লাইভ মেপ নেভিগেটৰ খোলক",
    "header.fieldReports": "ক্ষেত্ৰ ঘটনা প্ৰতিবেদন",
    "header.notifications": "জাননী",
    "header.markAllRead": "সকলো পঢ়া বুলি চিন দিয়ক",
    "header.noAlerts": "কোনো সক্ৰিয় সতৰ্কবাণী নাই — সকলো ঠিক আছে।",
    "header.settingsProfile": "ছেটিংছ আৰু প্ৰফাইল",
    "header.supportHelp": "সহায় আৰু সমৰ্থন",
    "header.signOut": "লগ আউট",
    "header.addConsignment": "কনছাইনমেন্ট যোগ কৰক",
    "header.operator": "পৰিবহণ অপাৰেটৰ",
    "header.subtitle": "আজি আপোনাৰ কাৰ্যকলাপত কি হৈ আছে।",
    "header.title": "প্ৰতিটো ডেলিভাৰী আগুৱাই নিওঁ।",

    // Dashboard View
    "dashboard.welcome": "স্বাগতম",
    "dashboard.subtitle": "আজি উত্তৰ-পূব অঞ্চলৰ বাস্তৱ সময়ৰ চোৰাংচোৱা তথ্য ইয়াত আছে।",
    "dashboard.dataSources": "তথ্যৰ উৎস",
    "dashboard.weather": "বতৰ",
    "dashboard.mlModels": "এমএল মডেল",
    "dashboard.vehicles": "যান-বাহন",
    "dashboard.gps": "জিপিএছ",
    "dashboard.live": "লাইভ",
    "dashboard.loaded": "লোড হ'ল",
    "dashboard.inDb": "তথ্যকোষত",
    "dashboard.positionsAvailable": "অৱস্থান উপলব্ধ",
    "dashboard.awaitingGps": "জিপিএছ তথ্যৰ বাবে অপেক্ষাৰত",
    "dashboard.totalRoutes": "মুঠ নিৰীক্ষিত পথ",
    "dashboard.routesAtRisk": "বিপদজনক পথ",
    "dashboard.blockedRoutes": "অৱৰুদ্ধ পথ",
    "dashboard.activeVehicles": "সক্ৰিয় বাহন",
    "dashboard.deliveriesInTransit": "পথত থকা ডেলিভাৰী",
    "dashboard.vsYesterday": "কালিৰ তুলনাত",

    // Common labels & buttons
    "common.goodMorning": "শুভ ৰাতিপুৱা",
    "common.goodAfternoon": "শুভ আবেলি",
    "common.goodEvening": "শুভ সন্ধ্যা",
    "common.active": "সক্ৰিয়",
    "common.resolved": "সমাধান হ'ল",
    "common.critical": "সংকটজনক",
    "common.high": "উচ্চ",
    "common.medium": "মধ্যম",
    "common.low": "নিম্ন",
    "common.viewAll": "সকলো চাওক",
    "common.cancel": "বাতিল কৰক",
    "common.save": "সংৰক্ষণ কৰক",
    "common.close": "বন্ধ কৰক",

    // Authentication Form
    "auth.welcomeBack": "স্বাগতম!",
    "auth.signInPrompt": "আগবাঢ়িবলৈ ছাইন ইন কৰক",
    "auth.official": "চৰকাৰী বিষয়া",
    "auth.transporter": "পৰিবহণকাৰী",
    "auth.driver": "চালক",
    "auth.emailOrPhone": "ইমেইল বা ফোন নম্বৰ",
    "auth.emailPlaceholder": "ইমেইল বা ফোন নম্বৰ দিয়ক",
    "auth.password": "পাছৱৰ্ড",
    "auth.passwordPlaceholder": "আপোনাৰ পাছৱৰ্ড দিয়ক",
    "auth.rememberMe": "মোক মনত ৰাখক",
    "auth.forgotPassword": "পাছৱৰ্ড পাহৰিলে নেকি?",
    "auth.signIn": "ছাইন ইন কৰক",
    "auth.signingIn": "ছাইন ইন হৈ আছে...",
    "auth.securityNotice": "চৰকাৰী ডুনাৰ লজিষ্টিকছ পৰ্টেল। ২৫৬-বিট এছএছএল সুৰক্ষিত।",
    "User Login": "ব্যৱহাৰকাৰী প্ৰৱেশ",
    "Official Login": "চৰকাৰী প্ৰৱেশ",
    "Operator Login": "পৰিবহণকাৰী প্ৰৱেশ",
  },
  bn: {
    // Navigation items (বাংলা)
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.live-map": "লাইভ ম্যাপ",
    "nav.ai-predictions": "এআই পূর্বাভাস",
    "nav.route-optimization": "রুট অপটিমাইজেশন",
    "nav.vehicle-tracking": "যানবাহন ট্র্যাকিং",
    "nav.alerts": "সতর্কতা ও বিজ্ঞপ্তি",
    "nav.field-reports": "ফিল্ড রিপোর্ট",
    "nav.analytics": "বিশ্লেষণ ও রিপোর্ট",
    "nav.users": "ব্যবহারকারী",
    "nav.emergency": "জরুরি অবস্থা",
    "nav.settings": "সেটিংস",
    "nav.consignments": "আমার কনসাইনমেন্ট",
    "nav.vehicles": "আমার যানবাহন",
    "nav.tracking": "লাইভ ট্র্যাকিং ও জিপিএস",
    "nav.fleet-tracking": "যানবাহন ট্র্যাকিং",
    "nav.routes": "রুট পরিকল্পনা",
    "nav.history": "ডেলিভারি ইতিহাস",
    "nav.reports": "রিপোর্ট ও বিশ্লেষণ",
    "nav.help": "সহায়তা ও সমর্থন",
    "nav.profile": "প্রোফাইল",
    "nav.adminPortal": "অ্যাডমিন পোর্টাল",
    "nav.transporterHub": "পরিবহন হাব",
    "nav.driverApp": "ড্রাইভার অ্যাপ",
    "nav.fieldOfficer": "ফিল্ড অফিসার",
    "nav.platform": "প্ল্যাটফর্ম",
    "nav.howItWorks": "এটি কিভাবে কাজ করে",
    "nav.intelligence": "বুদ্ধিমত্তা",
    "nav.solutions": "সমাধান",
    "nav.about": "সম্পর্কে",
    "nav.login": "লগইন",
    "nav.getStarted": "শুরু করুন",
    "nav.switch": "পরিবর্তন",
    "nav.logOut": "লগ আউট",
    "nav.signOut": "লগ আউট",

    // Sidebar Chrome
    "sidebar.brandTagline": "স্মার্ট রুট, নিরাপদ ডেলিভারি",
    "sidebar.quickActions": "দ্রুত পদক্ষেপ",
    "sidebar.addVehicle": "যানবাহন যোগ করুন",
    "sidebar.createAlert": "সতর্কতা তৈরি করুন",
    "sidebar.generateReport": "রিপোর্ট তৈরি করুন",
    "sidebar.importData": "ডেটা ইমপোর্ট করুন",
    "sidebar.systemStatus": "সিস্টেম অবস্থা",
    "sidebar.gpsTracking": "জিপিএস ট্র্যাকিং",
    "sidebar.dataSync": "ডেটা সিঙ্ক",
    "sidebar.aiEngine": "এআই ইঞ্জিন",
    "sidebar.serverStatus": "সার্ভার স্থিতি",
    "sidebar.online": "অনলাইন",
    "sidebar.offline": "অফলাইন",
    "sidebar.needHelp": "সাহায্য দরকার?",
    "sidebar.supportDesc": "আপনাকে সাহায্য করতে আমাদের টিম ২৪/৭ উপস্থিত।",
    "sidebar.contactSupport": "সহায়তায় যোগাযোগ করুন",
    "sidebar.liveMode": "লাইভ মোড",
    "sidebar.offlineMode": "অফলাইন মোড",
    "sidebar.liveDesc": "রিয়েল-টাইম ডেটা সক্রিয়",
    "sidebar.offlineDesc": "অনলাইন হলে ডেটা সিঙ্ক হবে",
    "sidebar.adminUser": "অ্যাডমিন ইউজার",
    "sidebar.adminRole": "সরকারি প্রশাসক",

    // Top Header Chrome
    "header.searchPlaceholder": "যানবাহন, রুট, চালক, সতর্কতা, রিপোর্ট খুঁজুন...",
    "header.logisticsGrid": "রাহী লজিস্টিক গ্রিড",
    "header.vehiclesActive": "টি যানবাহন সক্রিয়",
    "header.emergencySOS": "জরুরী এসওএস",
    "header.openLiveMap": "জিআইএস লাইভ ম্যাপ ন্যাভিগেটর খুলুন",
    "header.fieldReports": "ফিল্ড দুর্ঘটনা রিপোর্ট",
    "header.notifications": "বিজ্ঞপ্তি",
    "header.markAllRead": "সব পঠিত হিসেবে চিহ্নিত করুন",
    "header.noAlerts": "কোনো সক্রিয় সতর্কতা নেই — সব ঠিক আছে।",
    "header.settingsProfile": "সেটিংস ও প্রোফাইল",
    "header.supportHelp": "সহায়তা ও সমর্থন",
    "header.signOut": "লগ আউট",
    "header.addConsignment": "কনসাইনমেন্ট যোগ করুন",
    "header.operator": "পরিবহন অপারেটর",
    "header.subtitle": "আজ আপনার কার্যক্রমে যা ঘটছে।",
    "header.title": "প্রতিটি ডেলিভারি এগিয়ে নিয়ে যাই।",

    // Dashboard View
    "dashboard.welcome": "স্বাগতম",
    "dashboard.subtitle": "আজ উত্তর-পূর্বাঞ্চলের রিয়েল-টাইম বুদ্ধিমত্তা তথ্য এখানে।",
    "dashboard.dataSources": "ডেটা উৎস",
    "dashboard.weather": "আবহাওয়া",
    "dashboard.mlModels": "এমএল মডেল",
    "dashboard.vehicles": "যানবাহন",
    "dashboard.gps": "জিপিএস",
    "dashboard.live": "লাইভ",
    "dashboard.loaded": "লোড হয়েছে",
    "dashboard.inDb": "ডাটাবেসে",
    "dashboard.positionsAvailable": "অবস্থান উপলব্ধ",
    "dashboard.awaitingGps": "জিপিএস তথ্যের অপেক্ষায়",
    "dashboard.totalRoutes": "মোট পর্যবেক্ষণকৃত রুট",
    "dashboard.routesAtRisk": "ঝুঁকিপূর্ণ রুট",
    "dashboard.blockedRoutes": "অবরুদ্ধ রুট",
    "dashboard.activeVehicles": "সক্রিয় যানবাহন",
    "dashboard.deliveriesInTransit": "ট্রানজিটে থাকা ডেলিভারি",
    "dashboard.vsYesterday": "গতকালের তুলনায়",

    // Common labels & buttons
    "common.goodMorning": "শুভ সকাল",
    "common.goodAfternoon": "শুভ অপরাহ্ন",
    "common.goodEvening": "শুভ সন্ধ্যা",
    "common.active": "সক্রিয়",
    "common.resolved": "সমাধান হয়েছে",
    "common.critical": "সংকটজনক",
    "common.high": "উচ্চ",
    "common.medium": "মাঝারি",
    "common.low": "কম",
    "common.viewAll": "সব দেখুন",
    "common.cancel": "বাতিল",
    "common.save": "সংরক্ষণ",
    "common.close": "বন্ধ করুন",

    // Authentication Form
    "auth.welcomeBack": "স্বাগতম!",
    "auth.signInPrompt": "এগিয়ে যেতে সাইন ইন করুন",
    "auth.official": "আধিকারিক",
    "auth.transporter": "পরিবহনকারী",
    "auth.driver": "চালক",
    "auth.emailOrPhone": "ইমেল বা ফোন নম্বর",
    "auth.emailPlaceholder": "ইমেল বা ফোন নম্বর লিখুন",
    "auth.password": "পাসওয়ার্ড",
    "auth.passwordPlaceholder": "আপনার পাসওয়ার্ড লিখুন",
    "auth.rememberMe": "আমাকে মনে রাখুন",
    "auth.forgotPassword": "পাসওয়ার্ড ভুলে গেছেন?",
    "auth.signIn": "সাইন ইন",
    "auth.signingIn": "সাইন ইন হচ্ছে...",
    "auth.securityNotice": "অফিসিয়াল ডোনার লজিস্টিক পোর্টাল। ২৫৬-বিট এসএসএল সুরক্ষিত।",
    "User Login": "ব্যবহারকারী লগইন",
    "Official Login": "অফিসিয়াল লগইন",
    "Operator Login": "অপারেটর লগইন",
  },
  hi: {
    // Navigation items (हिन्दी)
    "nav.dashboard": "डैशबोर्ड",
    "nav.live-map": "लाइव मैप",
    "nav.ai-predictions": "एआई भविष्यवाणियाँ",
    "nav.route-optimization": "रूट ऑप्टिमाइज़ेशन",
    "nav.vehicle-tracking": "वाहन ट्रैकिंग",
    "nav.alerts": "चेतावनियाँ और सूचनाएँ",
    "nav.field-reports": "फ़ील्ड रिपोर्ट",
    "nav.analytics": "विश्लेषिकी और रिपोर्ट",
    "nav.users": "उपयोगकर्ता",
    "nav.emergency": "आपातकालीन मोड",
    "nav.settings": "सेटिंग्स",
    "nav.consignments": "मेरे कंसाइनमेंट",
    "nav.vehicles": "मेरे वाहन",
    "nav.tracking": "लाइव ट्रैकिंग और जीपीएस",
    "nav.fleet-tracking": "वाहन ट्रैकिंग",
    "nav.routes": "रूट योजना",
    "nav.history": "डिलीवरी इतिहास",
    "nav.reports": "रिपोर्ट और विश्लेषिकी",
    "nav.help": "सहायता और समर्थन",
    "nav.profile": "प्रोफ़ाइल",
    "nav.adminPortal": "एडमिन पोर्टल",
    "nav.transporterHub": "ट्रांसपोर्टर हब",
    "nav.driverApp": "ड्राइवर ऐप",
    "nav.fieldOfficer": "फील्ड ऑफिसर",
    "nav.platform": "प्लेटफ़ॉर्म",
    "nav.howItWorks": "यह कैसे काम करता है",
    "nav.intelligence": "इंटेलिजेंस",
    "nav.solutions": "समाधान",
    "nav.about": "हमारे बारे में",
    "nav.login": "लॉगिन",
    "nav.getStarted": "शुरू करें",
    "nav.switch": "बदलें",
    "nav.logOut": "लॉग आउट",
    "nav.signOut": "साइन आउट",

    // Sidebar Chrome
    "sidebar.brandTagline": "स्मार्ट मार्ग, सुरक्षित डिलीवरी",
    "sidebar.quickActions": "त्वरित कार्रवाई",
    "sidebar.addVehicle": "वाहन जोड़ें",
    "sidebar.createAlert": "चेतावनी बनाएँ",
    "sidebar.generateReport": "रिपोर्ट तैयार करें",
    "sidebar.importData": "डेटा आयात करें",
    "sidebar.systemStatus": "सिस्टम स्थिति",
    "sidebar.gpsTracking": "जीपीएस ट्रैकिंग",
    "sidebar.dataSync": "डेटा सिंक",
    "sidebar.aiEngine": "एआई इंजन",
    "sidebar.serverStatus": "सर्वर स्थिति",
    "sidebar.online": "ऑनलाइन",
    "sidebar.offline": "ऑफलाइन",
    "sidebar.needHelp": "मदद चाहिए?",
    "sidebar.supportDesc": "हमारी सहायता टीम आपकी मदद के लिए 24/7 उपलब्ध है।",
    "sidebar.contactSupport": "सहायता से संपर्क करें",
    "sidebar.liveMode": "लाइव मोड",
    "sidebar.offlineMode": "ऑफलाइन मोड",
    "sidebar.liveDesc": "रीयल-टाइम डेटा सक्रिय",
    "sidebar.offlineDesc": "ऑनलाइन होने पर डेटा सिंक होगा",
    "sidebar.adminUser": "एडमिन उपयोगकर्ता",
    "sidebar.adminRole": "सरकारी प्रशासक",

    // Top Header Chrome
    "header.searchPlaceholder": "वाहन, मार्ग, चालक, अलर्ट, रिपोर्ट खोजें...",
    "header.logisticsGrid": "राही लॉजिस्टिक्स ग्रिड",
    "header.vehiclesActive": "वाहन सक्रिय",
    "header.emergencySOS": "आपातकालीन एसओएस",
    "header.openLiveMap": "जीआईएस लाइव मैप नेविगेटर खोलें",
    "header.fieldReports": "फ़ील्ड घटना रिपोर्ट",
    "header.notifications": "सूचनाएँ",
    "header.markAllRead": "सभी पढ़ी हुई चिह्नित करें",
    "header.noAlerts": "कोई सक्रिय चेतावनी नहीं — सब ठीक है।",
    "header.settingsProfile": "सेटिंग्स और प्रोफ़ाइल",
    "header.supportHelp": "सहायता और समर्थन",
    "header.signOut": "साइन आउट",
    "header.addConsignment": "कंसाइनमेंट जोड़ें",
    "header.operator": "परिवहन संचालक",
    "header.subtitle": "आज आपके संचालन में क्या हो रहा है।",
    "header.title": "हर डिलीवरी को आगे बढ़ाएँ।",

    // Dashboard View
    "dashboard.welcome": "स्वागत है",
    "dashboard.subtitle": "आज उत्तर-पूर्वी क्षेत्र की रीयल-टाइम जानकारी यहाँ है।",
    "dashboard.dataSources": "डेटा स्रोत",
    "dashboard.weather": "मौसम",
    "dashboard.mlModels": "एमएल मॉडल",
    "dashboard.vehicles": "वाहन",
    "dashboard.gps": "जीपीएस",
    "dashboard.live": "लाइव",
    "dashboard.loaded": "लोड हुआ",
    "dashboard.inDb": "डेटाबेस में",
    "dashboard.positionsAvailable": "स्थितियां उपलब्ध",
    "dashboard.awaitingGps": "जीपीएस डेटा की प्रतीक्षा",
    "dashboard.totalRoutes": "कुल निगरानी किए गए मार्ग",
    "dashboard.routesAtRisk": "जोखिम में मार्ग",
    "dashboard.blockedRoutes": "अवरुद्ध मार्ग",
    "dashboard.activeVehicles": "सक्रिय वाहन",
    "dashboard.deliveriesInTransit": "पारगमन में डिलीवरी",
    "dashboard.vsYesterday": "कल की तुलना में",

    // Common labels & buttons
    "common.goodMorning": "सुप्रभात",
    "common.goodAfternoon": "शुभ दोपहर",
    "common.goodEvening": "शुभ संध्या",
    "common.active": "सक्रिय",
    "common.resolved": "समाधान हुआ",
    "common.critical": "अति गंभीर",
    "common.high": "उच्च",
    "common.medium": "मध्यम",
    "common.low": "सामान्य",
    "common.viewAll": "सभी देखें",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.close": "बंद करें",

    // Authentication Form
    "auth.welcomeBack": "स्वागत है!",
    "auth.signInPrompt": "आगे बढ़ने के लिए साइन इन करें",
    "auth.official": "अधिकारी",
    "auth.transporter": "ट्रांसपोर्टर",
    "auth.driver": "ड्राइवर",
    "auth.emailOrPhone": "ईमेल या फ़ोन नंबर",
    "auth.emailPlaceholder": "ईमेल या फ़ोन नंबर दर्ज करें",
    "auth.password": "पासवर्ड",
    "auth.passwordPlaceholder": "अपना पासवर्ड दर्ज करें",
    "auth.rememberMe": "मुझे याद रखें",
    "auth.forgotPassword": "पासवर्ड भूल गए?",
    "auth.signIn": "साइन इन",
    "auth.signingIn": "साइन इन हो रहा है...",
    "auth.securityNotice": "आधिकारिक डोनर लॉजिस्टिक्स पोर्टल। 256-बिट एसएसएल सुरक्षित।",
    "User Login": "उपयोगकर्ता लॉगिन",
    "Official Login": "अधिकारी लॉगिन",
    "Operator Login": "ऑपरेटर लॉगिन",
  },
  bdo: {
    // Navigation items (बड़ो)
    "nav.dashboard": "ডেশ্বোর্ড",
    "nav.live-map": "লাইভ মেপ",
    "nav.ai-predictions": "एआई सिगांथि",
    "nav.route-optimization": "लामा गोख्रों खालामनाय",
    "nav.vehicle-tracking": "गारि ट्रेकिं",
    "nav.alerts": "सांग्रांथि आरो खौरां",
    "nav.field-reports": "जायगा नायदिंनाय रिपर्ट",
    "nav.analytics": "बिजिरनाय आरो रिपर्ट",
    "nav.users": "बाहायग्राफोर",
    "nav.emergency": "गोख्रों थासारि",
    "nav.settings": "सेटिंफोर",
    "nav.consignments": "आंनि सामानफोर",
    "nav.vehicles": "आंनि गारिफोर",
    "nav.tracking": "লাইভ ट्रेकिं आरो जिपिएस",
    "nav.fleet-tracking": "गारि ट्रेकिं",
    "nav.routes": "लामा बिथांखि",
    "nav.history": "सामान दैथायनायनि जारिमिन",
    "nav.reports": "रिपर्ट आरो बिजिरनाय",
    "nav.help": "हेफाजाब आरो मद्दत",
    "nav.profile": "प्रफाइल",
    "nav.adminPortal": "एडमिन पर्टेल",
    "nav.transporterHub": "ट्रान्सपर्टार हब",
    "nav.driverApp": "सालाइग्रा एप",
    "nav.fieldOfficer": "जायगानि मावग्रा",
    "nav.platform": "मन्च",
    "nav.howItWorks": "बे माबोरै खामानि मावो",
    "nav.intelligence": "गियान",
    "nav.solutions": "राहा",
    "nav.about": "सोमोनदै",
    "nav.login": "हाबनाय",
    "nav.getStarted": "जागाय",
    "nav.switch": "सोलाय",
    "nav.logOut": "ओंखारलांनाय",
    "nav.signOut": "ओंखारलांनाय",

    // Sidebar Chrome
    "sidebar.brandTagline": "सोलोंगोनां लामा, रैखाथि दैथायनाय",
    "sidebar.quickActions": "गोख्रों खामानि",
    "sidebar.addVehicle": "गारि बाहाय",
    "sidebar.createAlert": "सांग्रांथि सोमजिहो",
    "sidebar.generateReport": "रिपर्ट बानाय",
    "sidebar.importData": "डाटा लाबो",
    "sidebar.systemStatus": "सिस्टेम थासारि",
    "sidebar.gpsTracking": "जिपिएस ट्रेकिं",
    "sidebar.dataSync": "डाटा ज' खालामनाय",
    "sidebar.aiEngine": "एआई इन्जिन",
    "sidebar.serverStatus": "सार्भार थासारि",
    "sidebar.online": "अनलाइन",
    "sidebar.offline": "अफलाइन",
    "sidebar.needHelp": "हेफाजाब नांगौ नामा?",
    "sidebar.supportDesc": "जोंनि हेफाजाब हान्जाया 24/7 नोंथांखौ मद्दत खालामनो दं।",
    "sidebar.contactSupport": "हेफाजाब लिनहर",
    "sidebar.liveMode": "लाइভ मद",
    "sidebar.offlineMode": "अफलाइन मद",
    "sidebar.liveDesc": "लाइভ डाटा जागायबाय",
    "sidebar.offlineDesc": "अनलाइन जाब्ला डाटा सिंक जागोन",
    "sidebar.adminUser": "एडमिन बाहायग्रा",
    "sidebar.adminRole": "सरकारि एडमिन",

    // Top Header Chrome
    "header.searchPlaceholder": "गारि, लामा, सालाइग्रा, सांग्रांथि, रिपर्ट नागिर...",
    "header.logisticsGrid": "राहि रजिरनाय ग्रिद",
    "header.vehiclesActive": "गारिफोर खामानिआव",
    "header.emergencySOS": "गोनांथार एसओएस",
    "header.openLiveMap": "जिआइएफ लाइভ মেপ खेव",
    "header.fieldReports": "जायगानि जाथाय रिपर्ट",
    "header.notifications": "जाननि",
    "header.markAllRead": "सब पঢ়ा চিন দি",
    "header.noAlerts": "জ’নো সক্ৰিয় সতর্ক নাই — सब ठीक আছে।",
    "header.settingsProfile": "ছেটিংছ আৰু প্ৰফাইল",
    "header.supportHelp": "সহায় আৰু সাপোৰ্ট",
    "header.signOut": "লগ-আউট",
    "header.addConsignment": "কনছাইনমেন্ট দি",
    "header.operator": "পৰিবহণ অপাৰেটৰ",
    "header.subtitle": "আজি আনি অফিচত কি হৈছে।",
    "header.title": "হায়েক ডেলিভাৰী এগৰিয়াই নিয়।",

    // Dashboard View
    "dashboard.welcome": "बरायबाय",
    "dashboard.subtitle": "दिनैनि सा-सान्जा ओनसोलनि लाइभ खौरां बेयाव दं।",
    "dashboard.dataSources": "डाटा फुंखाफोर",
    "dashboard.weather": "बारहावा",
    "dashboard.mlModels": "एम एल मदेलफोर",
    "dashboard.vehicles": "गारिफोर",
    "dashboard.gps": "जिपिएस",
    "dashboard.live": "लाइভ",
    "dashboard.loaded": "लद जाबाय",
    "dashboard.inDb": "डिबिआव",
    "dashboard.positionsAvailable": "जायगा मोनबाय",
    "dashboard.awaitingGps": "जिपिएस डाटा नेगासिनो",
    "dashboard.totalRoutes": "नायदिंनाय गासै लामाफोर",
    "dashboard.routesAtRisk": "खैफोदगोनां लामाफोर",
    "dashboard.blockedRoutes": "हेंथा गोनां लामाफोर",
    "dashboard.activeVehicles": "खामानिआव थानाय गारिफोर",
    "dashboard.deliveriesInTransit": "लामायाव थानाय सामानफोर",
    "dashboard.vsYesterday": "मैयानि रुजुनायाव",

    // Common labels & buttons
    "common.goodMorning": "গুদাম বেলি",
    "common.goodAfternoon": "গুদাম দুপৰ",
    "common.goodEvening": "গুদাম বেলাগ",
    "common.active": "जाबाय दं",
    "common.resolved": "मोजां जाबाय",
    "common.critical": "गोख्रों",
    "common.high": "गोजौ",
    "common.medium": "गेजेर",
    "common.low": "गाहाय",
    "common.viewAll": "गासैबो नाय",
    "common.cancel": "दानगार",
    "common.save": "दोनथुम",
    "common.close": "बन्द खालाम",

    // Authentication Form
    "auth.welcomeBack": "बरायबाय!",
    "auth.signInPrompt": "थांनो थाखाय साइन इन खालाम",
    "auth.official": "अफिसियेल",
    "auth.transporter": "ट्रान्सपर्टार",
    "auth.driver": "सालाइग्रा",
    "auth.emailOrPhone": "इमैल एबा फन नम्बर",
    "auth.emailPlaceholder": "इमैल एबा फन नम्बर लिर",
    "auth.password": "पासवर्ड",
    "auth.passwordPlaceholder": "नोंनि पासवर्ड लिर",
    "auth.rememberMe": "आंखौ गोसोआव लाखि",
    "auth.forgotPassword": "पासवर्ड बावबाय नामा?",
    "auth.signIn": "साइन इन",
    "auth.signingIn": "साइन इन जाबाय दं...",
    "auth.securityNotice": "सरकारि डनेर लजिस्टिक पर्टेल। 256-बिट एस एस एल रैखाथि।",
    "User Login": "बाहायग्रा हाबनाय",
    "Official Login": "अफिसियेल हाबनाय",
    "Operator Login": "अपारेटार हाबनाय",
  },
};

// Automatic reverse mapping: translates raw English phrases to the active language
const DICT_BY_VALUE = {};
Object.keys(DICT).forEach((langCode) => {
  DICT_BY_VALUE[langCode] = {};
  if (DICT.en) {
    Object.keys(DICT.en).forEach((key) => {
      const enVal = DICT.en[key];
      const transVal = DICT[langCode]?.[key];
      if (enVal && transVal) {
        DICT_BY_VALUE[langCode][enVal] = transVal;
      }
    });
  }
});

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "as", label: "Assamese (অসমীয়া)" },
  { code: "bn", label: "Bengali (বাংলা)" },
  { code: "hi", label: "Hindi (हिन्दी)" },
  { code: "bdo", label: "Bodo (बड़ो)" },
];

// Multilingual alert terms dictionary for northeastern logistics
const ALERT_TERMS = {
  en: {
    'Road Block': 'Road Block',
    'Road Blockage': 'Road Blockage',
    'Blocked Road': 'Blocked Road',
    'Landslide': 'Landslide',
    'Flood': 'Flood',
    'Flooded Road': 'Flooded Road',
    'Accident': 'Accident',
    'Vehicle Breakdown': 'Vehicle Breakdown',
    'Heavy Rainfall': 'Heavy Rainfall',
    'Traffic Jam': 'Traffic Jam',
    'Emergency SOS': 'Emergency SOS',
    'High-Risk Corridor': 'High-Risk Corridor',
    'Supply Gap': 'Supply Chain Disruption',
    'Critical': 'Critical',
    'High': 'High',
    'Medium': 'Medium',
    'Low': 'Low',
    'Resolved': 'Resolved',
    'Active': 'Active',
    'Caution': 'Caution advised',
    'Monitoring': 'Monitoring active',
  },
  as: {
    'Road Block': 'পথ অৱৰোধ',
    'Road Blockage': 'পথ অৱৰোধ',
    'Blocked Road': 'অৱৰুদ্ধ পথ',
    'Landslide': 'ভূমিস্খলন',
    'Flood': 'বানপানী',
    'Flooded Road': 'বানাক্ৰান্ত পথ',
    'Accident': 'দুৰ্ঘটনা',
    'Vehicle Breakdown': 'বাহন বিকল',
    'Heavy Rainfall': 'প্ৰচণ্ড বৰষুণ',
    'Traffic Jam': 'যান-জঁট',
    'Emergency SOS': 'জৰুৰীকালীন এছ.অ’.এছ',
    'High-Risk Corridor': 'উচ্চ-বিপদ সংকুল পথ',
    'Supply Gap': 'যোগান শৃংখল ব্যাঘাত',
    'Critical': 'সংকটজনক',
    'High': 'উচ্চ',
    'Medium': 'মধ্যম',
    'Low': 'নিম্ন',
    'Resolved': 'সমাধান হ’ল',
    'Active': 'সক্ৰিয়',
    'Caution': 'সাৱধানতা অৱলম্বন কৰক',
    'Monitoring': 'নিৰীক্ষণ চলি আছে',
  },
  bn: {
    'Road Block': 'রাস্তা অবরোধ',
    'Road Blockage': 'রাস্তা অবরোধ',
    'Blocked Road': 'অবরুদ্ধ রাস্তা',
    'Landslide': 'ভূমিধস',
    'Flood': 'বন্যা',
    'Flooded Road': 'বন্যা কবলিত রাস্তা',
    'Accident': 'দুর্ঘটনা',
    'Vehicle Breakdown': 'যানবাহন বিকল',
    'Heavy Rainfall': 'ভারী বৃষ্টিপাত',
    'Traffic Jam': 'যানজট',
    'Emergency SOS': 'জরুরী এসওএস',
    'High-Risk Corridor': 'উচ্চ-ঝুঁকিপূর্ণ করিডোর',
    'Supply Gap': 'সরবরাহ শৃঙ্খল বিঘ্ন',
    'Critical': 'সংকটজনক',
    'High': 'উচ্চ',
    'Medium': 'মাঝারি',
    'Low': 'কম',
    'Resolved': 'সমাধান হয়েছে',
    'Active': 'সক্রিয়',
    'Caution': 'সতর্কতা অবলম্বন করুন',
    'Monitoring': 'নজরদারি চলছে',
  },
  hi: {
    'Road Block': 'सड़क अवरोध',
    'Road Blockage': 'सड़क अवरोध',
    'Blocked Road': 'अवरुद्ध सड़क',
    'Landslide': 'भूस्खलन',
    'Flood': 'बाढ़',
    'Flooded Road': 'जलमग्न सड़क',
    'Accident': 'दुर्घटना',
    'Vehicle Breakdown': 'वाहन खराब',
    'Heavy Rainfall': 'भारी बारिश',
    'Traffic Jam': 'यातायात जाम',
    'Emergency SOS': 'आपातकालीन एसओएस',
    'High-Risk Corridor': 'अति-संवेदनशील कॉरिडोर',
    'Supply Gap': 'आपूर्ति श्रृंखला व्यवधान',
    'Critical': 'अति गंभीर',
    'High': 'उच्च',
    'Medium': 'मध्यम',
    'Low': 'सामान्य',
    'Resolved': 'समाधान हुआ',
    'Active': 'सक्रिय',
    'Caution': 'सावधानी बरतें',
    'Monitoring': 'निगरानी जारी',
  },
  bdo: {
    'Road Block': 'लामा हेंथा',
    'Road Blockage': 'लामा हेंथा',
    'Blocked Road': 'हेंथा गोनां लामा',
    'Landslide': 'हा खनाय',
    'Flood': 'दै बाना',
    'Flooded Road': 'दै गोनां लामा',
    'Accident': 'खैफोद',
    'Vehicle Breakdown': 'गाड़ी गाज्रि जाबाय',
    'Heavy Rainfall': 'गोख्रों अखा',
    'Traffic Jam': 'थांनाय-फैनाय हेंथा',
    'Emergency SOS': 'गोनांथार एसओएस',
    'High-Risk Corridor': 'गिख्रों लामा',
    'Supply Gap': 'रसद खहा',
    'Critical': 'गोख्रों',
    'High': 'गोजौ',
    'Medium': 'गेजेर',
    'Low': 'गाहाय',
    'Resolved': 'मोजां जाबाय',
    'Active': 'जाबाय दं',
    'Caution': 'सावदान था',
    'Monitoring': 'नायगिरबाय दं',
  },
};

/** Translate alert title, message, and severity to active language */
export const localizeAlert = (alert, lang = 'en') => {
  if (!alert) return alert;
  if (!lang || lang === 'en') return alert;

  const dict = ALERT_TERMS[lang] || ALERT_TERMS.en;
  let title = alert.title || '';
  let message = alert.message || '';
  let severity = alert.severity || '';

  const rawSev = String(severity).toLowerCase();
  if (rawSev === 'high' && dict['High']) severity = dict['High'];
  else if (rawSev === 'critical' && dict['Critical']) severity = dict['Critical'];
  else if (rawSev === 'medium' && dict['Medium']) severity = dict['Medium'];
  else if (rawSev === 'low' && dict['Low']) severity = dict['Low'];

  Object.keys(ALERT_TERMS.en).forEach((enTerm) => {
    const localized = dict[enTerm];
    if (localized && localized !== enTerm) {
      const regex = new RegExp(enTerm, 'gi');
      title = title.replace(regex, localized);
      message = message.replace(regex, localized);
    }
  });

  return {
    ...alert,
    title,
    message,
    severity,
  };
};

const LanguageContext = createContext(undefined);

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    try {
      return localStorage.getItem("raahi_lang") || "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem("raahi_lang", lang);
    } catch { /* storage unavailable */ }
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (code) => {
    const c = DICT[code] ? code : "en";
    setLangState(c);
  };

  const t = (key) => {
    if (!key || typeof key !== 'string') return key;
    const table = DICT[lang] || DICT.en;
    if (table[key] !== undefined) return table[key];
    if (DICT.en[key] !== undefined) return DICT.en[key];
    if (DICT_BY_VALUE[lang]?.[key]) return DICT_BY_VALUE[lang][key];
    return key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, LANGUAGES, localizeAlert }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used inside LanguageProvider");
  return ctx;
};

export default LanguageProvider;